<?php
/**
 * Campaign Detail - Posts Tab Template
 *
 * Displays posts generated by this campaign.
 *
 * @package AutoBlogCraft_AI
 * @subpackage Templates\Admin\Campaign_Detail
 * @since 2.0.0
 *
 * @var object $campaign Campaign object
 * @var array $posts Campaign posts
 * @var object $pagination Pagination data
 * @var array $filters Active filters
 */

defined('ABSPATH') || exit;

$campaign = $campaign ?? null;
$posts = $posts ?? [];
$pagination = $pagination ?? (object) ['total' => 0, 'per_page' => 20, 'current_page' => 1];
$filters = $filters ?? [];

if (!$campaign) {
	return;
}
?>

<div class="abc-campaign-posts">
	<!-- Posts Filters -->
	<div class="abc-posts-filters">
		<form method="get" class="abc-filters-form">
			<input type="hidden" name="page" value="<?php echo esc_attr($_GET['page'] ?? ''); ?>">
			<input type="hidden" name="action" value="detail">
			<input type="hidden" name="id" value="<?php echo esc_attr($campaign->ID); ?>">
			<input type="hidden" name="tab" value="posts">
			
			<div class="abc-filter-group">
				<label for="filter-post-status"><?php esc_html_e('Status:', 'autoblogcraft-ai'); ?></label>
				<select name="post_status" id="filter-post-status">
					<option value=""><?php esc_html_e('All Statuses', 'autoblogcraft-ai'); ?></option>
					<option value="publish" <?php selected($filters['status'] ?? '', 'publish'); ?>><?php esc_html_e('Published', 'autoblogcraft-ai'); ?></option>
					<option value="draft" <?php selected($filters['status'] ?? '', 'draft'); ?>><?php esc_html_e('Draft', 'autoblogcraft-ai'); ?></option>
					<option value="pending" <?php selected($filters['status'] ?? '', 'pending'); ?>><?php esc_html_e('Pending', 'autoblogcraft-ai'); ?></option>
				</select>
			</div>

			<div class="abc-filter-group abc-filter-search">
				<label for="filter-search" class="screen-reader-text"><?php esc_html_e('Search posts', 'autoblogcraft-ai'); ?></label>
				<input type="search" name="s" id="filter-search" 
				       value="<?php echo esc_attr($filters['search'] ?? ''); ?>" 
				       placeholder="<?php esc_attr_e('Search posts...', 'autoblogcraft-ai'); ?>">
			</div>

			<button type="submit" class="button"><?php esc_html_e('Filter', 'autoblogcraft-ai'); ?></button>
		</form>

		<div class="abc-posts-actions">
			<a href="<?php echo esc_url(admin_url('edit.php?abc_campaign_id=' . $campaign->ID)); ?>" class="button">
				<span class="dashicons dashicons-external"></span>
				<?php esc_html_e('View in Posts List', 'autoblogcraft-ai'); ?>
			</a>
		</div>
	</div>

	<!-- Posts Table -->
	<?php if (!empty($posts)) : ?>
		<table class="wp-list-table widefat fixed striped abc-posts-table">
			<thead>
				<tr>
					<th class="manage-column column-title column-primary"><?php esc_html_e('Title', 'autoblogcraft-ai'); ?></th>
					<th class="manage-column column-status"><?php esc_html_e('Status', 'autoblogcraft-ai'); ?></th>
					<th class="manage-column column-category"><?php esc_html_e('Categories', 'autoblogcraft-ai'); ?></th>
					<th class="manage-column column-date"><?php esc_html_e('Published', 'autoblogcraft-ai'); ?></th>
					<th class="manage-column column-views"><?php esc_html_e('Views', 'autoblogcraft-ai'); ?></th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($posts as $post) : ?>
					<tr>
						<td class="column-title column-primary" data-colname="<?php esc_attr_e('Title', 'autoblogcraft-ai'); ?>">
							<strong>
								<a href="<?php echo esc_url(get_edit_post_link($post->ID)); ?>">
									<?php echo esc_html($post->post_title); ?>
								</a>
							</strong>
							<div class="row-actions">
								<span class="edit">
									<a href="<?php echo esc_url(get_edit_post_link($post->ID)); ?>">
										<?php esc_html_e('Edit', 'autoblogcraft-ai'); ?>
									</a> |
								</span>
								<span class="view">
									<a href="<?php echo esc_url(get_permalink($post->ID)); ?>" target="_blank" rel="noopener">
										<?php esc_html_e('View', 'autoblogcraft-ai'); ?>
									</a> |
								</span>
								<span class="trash">
									<a href="<?php echo esc_url(get_delete_post_link($post->ID)); ?>" class="submitdelete">
										<?php esc_html_e('Trash', 'autoblogcraft-ai'); ?>
									</a>
								</span>
							</div>
						</td>
						<td class="column-status" data-colname="<?php esc_attr_e('Status', 'autoblogcraft-ai'); ?>">
							<span class="abc-status abc-status-<?php echo esc_attr($post->post_status); ?>">
								<?php echo esc_html(ucfirst($post->post_status)); ?>
							</span>
						</td>
						<td class="column-category" data-colname="<?php esc_attr_e('Categories', 'autoblogcraft-ai'); ?>">
							<?php 
							$categories = get_the_category($post->ID);
							if (!empty($categories)) {
								$cat_names = array_map(function($cat) {
									return $cat->name;
								}, $categories);
								echo esc_html(implode(', ', $cat_names));
							} else {
								echo '—';
							}
							?>
						</td>
						<td class="column-date" data-colname="<?php esc_attr_e('Published', 'autoblogcraft-ai'); ?>">
							<?php if ($post->post_status === 'publish') : ?>
								<?php echo esc_html(date_i18n(get_option('date_format'), strtotime($post->post_date))); ?>
								<br>
								<small><?php echo esc_html(human_time_diff(strtotime($post->post_date), current_time('timestamp'))); ?> <?php esc_html_e('ago', 'autoblogcraft-ai'); ?></small>
							<?php else : ?>
								<?php esc_html_e('Not published', 'autoblogcraft-ai'); ?>
							<?php endif; ?>
						</td>
						<td class="column-views" data-colname="<?php esc_attr_e('Views', 'autoblogcraft-ai'); ?>">
							<?php 
							$views = get_post_meta($post->ID, '_abc_post_views', true);
							echo esc_html($views ? number_format_i18n($views) : '0');
							?>
						</td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>

		<!-- Pagination -->
		<?php if ($pagination->total > $pagination->per_page) : ?>
			<div class="abc-pagination">
				<?php
				$total_pages = ceil($pagination->total / $pagination->per_page);
				$current_page = $pagination->current_page;
				
				echo paginate_links([
					'base' => add_query_arg('paged', '%#%'),
					'format' => '',
					'prev_text' => __('&laquo; Previous', 'autoblogcraft-ai'),
					'next_text' => __('Next &raquo;', 'autoblogcraft-ai'),
					'total' => $total_pages,
					'current' => $current_page,
					'type' => 'plain',
				]);
				?>
			</div>
		<?php endif; ?>
	<?php else : ?>
		<div class="abc-empty-state">
			<span class="dashicons dashicons-edit"></span>
			<h3><?php esc_html_e('No posts yet', 'autoblogcraft-ai'); ?></h3>
			<p><?php esc_html_e('Posts will appear here when they are generated from the queue.', 'autoblogcraft-ai'); ?></p>
		</div>
	<?php endif; ?>
</div>
